org: yakubu
service: devops-cicd

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 512
  timeout: 10

  httpApi:
    cors: true

functions:
  helloWorld:
    handler: src/hello/hello.helloWorld
    events:
      - httpApi:
          path: /hello
          method: get

plugins:
  - serverless-offline
